### ISSUE TITLE
Failed to parse component during `vuese gen`

### ISSUE THREAD

**Issue by adjenks** [HcySunYang/vuese#130]
**Describe the bug**
Calling `vuese gen` produced an error and the component was not rendered.

**To Reproduce**
1. Install vuese
2. Call `vuese gen` at document root.

**Expected behavior**
No errors.

**Environmental information:**
Environment Info:

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
  Binaries:
    Node: 10.8.0 - /var/---/bin/node
    npm: 6.11.3 - /var/---/bin/npm

**Additional information**

> Add any other information about the problem here.
> �  The error occurred when processing: /var/www/---/---/my-app/src/components/OPickList.vue
> �  TypeError: Cannot read property 'filter' of undefined
>     at ObjectProperty (/var/www/---/node_modules/@vuese/parser/dist/index.js:653:61)
>     at NodePath._call (/var/www/---/node_modules/@babel/traverse/lib/path/context.js:53:20)
>     at NodePath.call (/var/www/---/node_modules/@babel/traverse/lib/path/context.js:40:17)
>     at NodePath.visit (/var/www/---/node_modules/@babel/traverse/lib/path/context.js:88:12)
>     at TraversalContext.visitQueue (/var/www/---/node_modules/@babel/traverse/lib/context.js:120:16)
>     at TraversalContext.visitMultiple (/var/www/---/node_modules/@babel/traverse/lib/context.js:87:17)
>     at TraversalContext.visit (/var/www/---/node_modules/@babel/traverse/lib/context.js:146:19)
>     at Function.traverse.node (/var/www/---/node_modules/@babel/traverse/lib/index.js:96:17)
>     at NodePath.visit (/var/www/---/node_modules/@babel/traverse/lib/path/context.js:95:18)
>     at TraversalContext.visitQueue (/var/www/---/node_modules/@babel/traverse/lib/context.js:120:16)
> 

Might be related to: https://github.com/babel/babel/issues/9495

**Comment by adjenks** [comment]
Note: Some components worked, some did not. Also, I'd rather not give you my code, but I might slim the component down to find out where the error is later. I just wanted to open the ticket for now with the basics.

**Comment by adjenks** [comment]
I have discovered the following:

Defining the data function like this results in an error:
```js
data: () => {
  return {}
}
```
Defining it like this does not result in an error:
```js
data() {
  return {}
}
```

**Comment by adjenks** [comment]
Awesome, thank you.
