### ISSUE TITLE
TypeError: Cannot read property 'compName' of undefined

### ISSUE THREAD

**Issue by proshuai** [HcySunYang/vuese#15]
TypeError: Cannot read property 'compName' of undefined
    at componentRes.map.res (/Users/aaa/.config/yarn/global/node_modules/vuese/lib/genDocute.js:11:18)
    at Array.map (<anonymous>)
    at module.exports (/Users/aaa/.config/yarn/global/node_modules/vuese/lib/genDocute.js:10:41)
    at <anonymous>

**Comment by proshuai** [comment]
vuese.config.js
`module.exports = {
  include: [
    "src/components/**/*.vue",
    "src/pages/**/*.vue"
  ],
  outDir: 'docs',
  genType: 'docute'
}`

**Comment by HcySunYang** [comment]
Can you provide a component that can reproduce the problem? Minimal implementation, if your code is not convenient to expose, you can try to modify and find the minimum reproduction
