### ISSUE TITLE
Cannot find module 'vue-template-compiler/build'

### ISSUE THREAD

**Issue by OwenShi** [HcySunYang/vuese#176]
**Describe the bug**
after `yarn global add @vuese/cli`, use the cammand `vuese` or `vuese --version` or `vuese gen` and so on.
it cannot work and the error message like this:

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'vue-template-compiler/build'
Require stack:
- /Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/node_modules/@vuese/parser/dist/index.js
- /Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/dist/index.js
- /Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/node_modules/@vuese/parser/dist/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/node_modules/@vuese/parser/dist/index.js',
    '/Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/dist/index.js',
    '/Users/shiwj/.nvm/versions/node/v14.4.0/lib/node_modules/@vuese/cli/bin/index.js'
  ]
}

**Environmental information:**
@vuese/cli@ v2.13.1
node v14.4.0
npm v6.14.5

**Comment by IWANABETHATGUY** [comment]
Have you try to remove the node_modules , and reinstall ?
i can't reproduce it.

**Comment by OwenShi** [comment]
The first time I found this problem was in gitlab-ci with docker，that should be a new environment every time。
then i test it in my macOS, the problem still occurs。

I just test it in a new window environment there are no node, no npm and no vuese, and the problem still occurs。

in Windows my steps are as follows:
1 `download nodejs`
2 `npm install -g yarn`
3  add yarn to the environment path
4  `yarn global add @vuese/cli`
5  `vuese` or `vuese --version`

**Comment by OwenShi** [comment]
i try to remove the node_modules or reinstall, but doesn't seem to work
