### ISSUE TITLE
loader.js 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by MattiaFailla** [HcySunYang/vuese#182]
**Describe the bug**
I have installed vuese via this command:
`yarn global add @vuese/cli` but something is missing.

**To Reproduce**
Just run `vuese gen`

**Expected behavior**
Expecting doc. generation

**Environmental information:**
Unable to run `vuese info` because of the same error

**Additional information**
The output is the following:
```
 % vuese gen                 
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/home/mat/.nvm/versions/node/v13.6.0/lib/node_modules/@vuese/cli/node_modules/cac'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/mat/.nvm/versions/node/v13.6.0/lib/node_modules/@vuese/cli/dist/index.js:5:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}

```

I have already tried to remove `node_modules` and reinstall.

**Comment by adairzf** [comment]
I see that this issues has been resolved.When can I update the yarn version

**Comment by MattiaFailla** [comment]
My `yarn` version is `1.22.4`

**Comment by IWANABETHATGUY** [comment]
- @vuese/cli@2.14.0
would fix this problem

**Comment by IWANABETHATGUY** [comment]
If you have any  other problem , you could reopen this issue
