### ISSUE TITLE
The environment variable CHROME_PATH must be set to executable of a build of Chromium

### ISSUE THREAD

**Issue by NeonWizard** [HcySunYang/vuese#231]
**Describe the bug**
When executing `vuese preview path/to/file`, I get the following error:
```
(node:6786) UnhandledPromiseRejectionWarning: Error: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
    at linux (REDACTED/node_modules/carlo/lib/find_chrome.js:84:11)
    at findChrome (REDACTED/node_modules/carlo/lib/find_chrome.js:230:24)
    at Object.launch (REDACTED/node_modules/carlo/lib/carlo.js:594:42)
    at module.exports (REDACTED/node_modules/vuese/lib/preview.js:27:29)
    at Command.cli.command [as handler] (REDACTED/node_modules/vuese/bin/cli.js:46:30)
(node:6786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. `npm install -g vuese`
2. `vuese preview path/to/file`

**Environmental information:**
```
> vuese -v
1.4.7
```
Running on WSL2

**Comment by Viggo95** [comment]
@NeonWizard 

### Please provide the version of @vuese/cli
you can enter the following command in terminal
``` js
vuese -v
```
> If you are not globally installed, you can `npx vuese -v`


<br>
<br>

### Better give me a screenshot
like this
![image](https://user-images.githubusercontent.com/22092110/116351422-3b2d9a00-a826-11eb-87e4-c89e14830424.png)



<br>
<br>

### Solve this problem
After my testing, it works fine in version 2.14.x, so you can fix it like this
- Install the latest version of @vuese/cli
- Make sure the version is 2.14.x
- `vuese preview filename.vue`

![image](https://user-images.githubusercontent.com/22092110/116351492-5ef0e000-a826-11eb-9620-2b01234b2c99.png)


``` js
yarn global remove @vuese/cli

yarn global add @vuese/cli
```

**Comment by NeonWizard** [comment]
> @NeonWizard
> 
> ### Please provide the version of @vuese/cli
> you can enter the following command in terminal
> 
> ```js
> vuese -v
> ```
> 
> > If you are not globally installed, you can `npx vuese -v`
> 
> 
> 
> ### Better give me a screenshot
> like this
> 
> 
> ### Solve this problem
> After my testing, it works fine in version 2.14.x, so you can fix it like this
> 
> * Install the latest version of @vuese/cli
> * Make sure the version is 2.14.x
> * `vuese preview filename.vue`
> 
> 
> ```js
> yarn global remove @vuese/cli
> 
> yarn global add @vuese/cli
> ```

I'm pretty sure it doesn't work because it's being used on WSL. Your solution does not work.

**Comment by NeonWizard** [comment]
@screetBloom I'm still having the issue. My original post includes the version used, all the information to reproduce, the machine it's running on, etc. I'm not entirely sure why you removed the bug label.

@HcySunYang

**Comment by NeonWizard** [comment]
You may want to reference this, if you haven't added WSL support to this library.

https://github.com/GoogleChrome/chrome-launcher/pull/27

**Comment by NeonWizard** [comment]
@screetBloom @HcySunYang Bump. Just a reminder this issue was incorrectly marked as having a solution.
