### ISSUE TITLE
Package version mismatch on new Vue 3 project.

### ISSUE THREAD

**Issue by DanielRunningen** [HcySunYang/vuese#269]
**Describe the bug**
Package version mismatch on new Vue 3 project.

**To Reproduce**
1. Create new project with `vue create`, selecting Vue 3. (I also included dart-sass, babel, typescript, router, vuex, and eslint.)
2. Enter project and add vuese with `npm i --save-dev vuese`.
3. Add a script command to `package.json` like `"docs": "vuese gen"`.
4. Run `npm run docs`.

**Expected behavior**
Build should succeed.

**Screenshots**
![image](https://github.com/vuese/vuese/assets/7986196/9a9664e2-1f93-454c-a9f0-b2f54243342c)

Stack trace:
```
    at Object.<anonymous> (~/Desktop/test/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/home/dan/Desktop/test/node_modules/vuese/dist/vuese.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
```

**Environmental information:**
```
> vuese info


  vuese * 1.4.7

  vuese cli

  USAGE

    vuese * [options]

  GLOBAL OPTIONS

    -v, --version  Display version                     [Type: boolean]
    -h, --help     Display help (You're already here)  [Type: boolean]
```

**Additional information**
I haven't seen any requirements for what versions of Vue might be supported and which are not... There also doesn't seem to be any information on which versions of either `vue-loader` or `vue-template-compiler` would be required to use this package, just that whatever is installed isn't supported.

**Comment by wyy9630** [comment]
@Chunyang Huo 希望能早日支持vue3

**Comment by wyy9630** [comment]
@HcySunYang  希望能早日支持vue3
