### ISSUE TITLE
在vue-cli3中使用ts的get方法，无法生成该方法的说明

### ISSUE THREAD

**Issue by cykcykcykcyk** [HcySunYang/vuese#42]
```
// @vuese
// 获取标题栏高度，可以使用self.getBarHeight(),也可以使用self.barHeight返回
public get barHeight(): number {
            return this.navBar.offsetHeight;
 }
```

以上代码无法识别

另外使用这样的写法在生成文档的时候会报错
```
public get barHeight(): number {
            return (<any>this).$refs.navBar.offsetHeight;
 }
```
虽然可以通过这样的改写，达到效果，但是感觉多绕了一下，希望可以支持<any>强制类型转化
```
private mounted() {
            this.navBar = this.$refs.navBar;
 }
 // @vuese
// 获取标题栏高度，可以使用self.getBarHeight(),也可以使用self.barHeight返回
public getBarHeight(): number {
            return this.navBar.offsetHeight;
}

 public get barHeight(): number {
            return this.navBar.offsetHeight;
}
```

控制台信息:
The error occurred when processing: /Volumes/CHEN YANKAI/sourceCode/vueProject/simple-mall/src/components/NavBar.vue
SyntaxError: Unexpected token (38:8)
    at Object.raise (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.parseExprAtom (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:6283:20)
    at Object.parseExprAtom (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:3552:20)
    at Object.parseExprSubscripts (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5862:23)
    at Object.parseMaybeUnary (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5842:21)
    at Object.parseMaybeUnary (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:10403:20)
    at Object.parseExprOps (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5729:23)
    at Object.parseMaybeConditional (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5702:23)
    at Object.parseMaybeAssign (/usr/local/lib/node_modules/@vuese/cli/node_modules/@babel/parser/lib/index.js:5647:21)
Successfully created: /Volumes/CHEN YANKAI/sourceCode/vueProject/simple-mall/website/components/Badge.md
Successfully created: /Volumes/CHEN YANKAI/sourceCode/vueProject/simple-mall/website/components/FilletCard.md
Successfully created: /Volumes/CHEN YANKAI/sourceCode/vueProject/simple-mall/website/components/NumberBox.md
Successfully created: /Volumes/CHEN YANKAI/sourceCode/vueProject/simple-mall/website/components/Grid.md
 Start generating...

**Comment by HcySunYang** [comment]
这是一个 bug，看上去是由 public modifier 导致的。
临时解决方案：你可以去掉 public modifier。

**Comment by HcySunYang** [comment]
This issue has been resolved: use `@vuese/cli@2.2.4`.
Note: In order to use `<Type>Var` in TS, you need to add the following configuration to `.vueserc`:
```js
{
  // ...
  "babelParserPlugins": {
    "jsx": false
  }
}
```

**Comment by cykcykcykcyk** [comment]
thx， 我试下看看

**Comment by cykcykcykcyk** [comment]
可以了
