### ISSUE TITLE
Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by yyman001** [HcySunYang/vuese#8]
```cmd
E:\git\web-material-user@last (v1-scene -> origin)                                                            
λ vuese gen --include="components/*.vue"                                                                      
? Select the target to generate Only markdown.                                                                
∞ Start creating markdown files...                                                                            
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 1)                                                                                  
(node:78728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise
 rejections that are not handled will terminate the Node.js process with a non-zero exit code.                
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 2)                                                                                  
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 3)                                                                                  
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 4)                                                                                  
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 5)                                                                                  
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
 .catch(). (rejection id: 6)                                                                                  
(node:78728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined        
    at Object.comment (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:2575:21)                                                                                                    
    at parseHTML (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:345
:23)                                                                                                          
    at parse (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:2402:3)
    at baseCompile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.js:4
267:13)                                                                                                       
    at Object.compile (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vue-template-compiler\build.j
s:4242:22)                                                                                                    
    at sfcToAST (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:28:47)         
    at parser$1 (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\dist\vuese.js:401:20)        
    at files.map (C:\Users\XF\AppData\Local\Yarn\config\global\node_modules\vuese\lib\index.js:30:23)         
    at <anonymous>                                                                                            
(node:78728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by th
rowing inside of an async function without a catch block, or by rejecting a promise which was not handled with
√ Successfully created: E:\git\web-material-user@last\website\components\project-material.md                  
√ Successfully created: E:\git\web-material-user@last\website\components\button-demo.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\codeButton.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-test.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\screenButton.md                      
√ Successfully created: E:\git\web-material-user@last\website\components\v-script.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\app.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\z-dialog.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\feedback.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\module-static2d.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\guide.md                             
√ Successfully created: E:\git\web-material-user@last\website\components\module-panorama.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-test.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\demo-dialog-confirm.md               
√ Successfully created: E:\git\web-material-user@last\website\components\page-404.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\library-preview.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\module-static2d.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\guide-logic.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\transform-tools.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\registry.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\pixi-canvas-extend.md                
√ Successfully created: E:\git\web-material-user@last\website\components\transformRect.md                     
√ Successfully created: E:\git\web-material-user@last\website\components\pixi-canvas.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\registry.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\pixi-canvas-extend.md                
√ Successfully created: E:\git\web-material-user@last\website\components\registryTab.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\vue-rulers.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\pixi-canvas-scene.md                 
√ Successfully created: E:\git\web-material-user@last\website\components\app.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\registry-from.md                     
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-code.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\accordionMenu-flagColor-warp.md      
√ Successfully created: E:\git\web-material-user@last\website\components\registry-from.md                     
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-code.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\page-tab-level2.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\dm-button-group.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\STabPanel.md                         
√ Successfully created: E:\git\web-material-user@last\website\components\z-dialog.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\dm-icon.md                           
√ Successfully created: E:\git\web-material-user@last\website\components\page-tab.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\vddl-handle.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\vddl-draggable.md                    
√ Successfully created: E:\git\web-material-user@last\website\components\dm-header.md                         
√ Successfully created: E:\git\web-material-user@last\website\components\SIcon.md                             
√ Successfully created: E:\git\web-material-user@last\website\components\vddl-placeholder.md                  
√ Successfully created: E:\git\web-material-user@last\website\components\export-all-expression.md             
√ Successfully created: E:\git\web-material-user@last\website\components\export-list.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\topBar.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\vddl-nodrag.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\dm-layout.md                         
√ Successfully created: E:\git\web-material-user@last\website\components\vddl-list.md                         
√ Successfully created: E:\git\web-material-user@last\website\components\app.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\export-icon.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\dm-loading.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\app.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\export-null.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\export-dialog-pay.md                 
√ Successfully created: E:\git\web-material-user@last\website\components\app.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\price-view.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\v-price.md                           
√ Successfully created: E:\git\web-material-user@last\website\components\bubble.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\single.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\dm-scene-static2d.md                 
√ Successfully created: E:\git\web-material-user@last\website\components\index.md                             
√ Successfully created: E:\git\web-material-user@last\website\components\coupons-empty.md                     
√ Successfully created: E:\git\web-material-user@last\website\components\order-table.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\order-page.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\demo-b.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\coupons-table.md                     
√ Successfully created: E:\git\web-material-user@last\website\components\history-button.md                    
√ Successfully created: E:\git\web-material-user@last\website\components\order-empty.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\frame-switch.md                      
√ Successfully created: E:\git\web-material-user@last\website\components\personal-center.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\order-table-row.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-project.md                    
√ Successfully created: E:\git\web-material-user@last\website\components\layer-card.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\dm-context-menu.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\panel-layer.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\tab-switch-view.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\export-page.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\dm-accordion-menu.md                 
√ Successfully created: E:\git\web-material-user@last\website\components\dm-tab.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\dialog-test.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\subTab.md                            
√ Successfully created: E:\git\web-material-user@last\website\components\progressBar.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\dm-button.md                         
√ Successfully created: E:\git\web-material-user@last\website\components\initDialog.md                        
√ Successfully created: E:\git\web-material-user@last\website\components\a-search.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\svg-simple-icon.md                   
√ Successfully created: E:\git\web-material-user@last\website\components\panel.md                             
√ Successfully created: E:\git\web-material-user@last\website\components\iscroll-view.md                      
√ Successfully created: E:\git\web-material-user@last\website\components\Tab.md                               
√ Successfully created: E:\git\web-material-user@last\website\components\Tabs.md                              
√ Successfully created: E:\git\web-material-user@last\website\components\scroll-view.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\panel-group.md                       
√ Successfully created: E:\git\web-material-user@last\website\components\svg-icon.md                          
√ Successfully created: E:\git\web-material-user@last\website\components\dm-project.md                        
                                                                                                              
```

**Comment by HcySunYang** [comment]
It seems to be a problem with template writing. Have you used `<slot>` as the root element and there is a comment node before `<slot>`? I just made a patch and you can install `vue@1.1.1`, which tells you error occurred while processing which component.
